<?php

/**
 * BaseTipo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * @property User $User
 * 
 * @method integer getId()     Returns the current record's "id" value
 * @method string  getNombre() Returns the current record's "nombre" value
 * @method User    getUser()   Returns the current record's "User" value
 * @method Tipo    setId()     Sets the current record's "id" value
 * @method Tipo    setNombre() Sets the current record's "nombre" value
 * @method Tipo    setUser()   Sets the current record's "User" value
 * 
 * @package    galeno
 * @subpackage model
 * @author     Enimados
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTipo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tipo');
        $this->hasColumn('id', 'integer', 6, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 6,
             ));
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('User', array(
             'local' => 'id',
             'foreign' => 'tipo_id'));
    }
}