<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/09/27 19:16:13

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=xerocare',
  'username' => 'root',
  'password' => 'root',
  'name' => 'doctrine',
)),);
