# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: contenido, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*

usuarionuevo:
  url:   /usuario/new
  param: { module: usuario, action: new }

outLogin:
  url:   /usuario/outLogin
  param: { module: usuario, action: outLogin }

preLogin:
  url:   /usuario/preLogin
  param: { module: usuario, action: preLogin }
  
proImc:
  url:   /imc/proImc
  param: { module: imc, action: proImc }

construccion:
  url:   /contenido/construccion
  param: { module: contenido, action: construccion }

triptico:
  url:   /contenido/inicio
  param: { module: contenido, action: inicio }

ayuda:
  url:   /ayuda
  param: { module: ayuda, action: index }

imc:
  url:   /imc
  param: { module: imc, action: index }

search:
  url:   /ayuda/search
  param: { module: ayuda, action: search }