<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Noticia', 'doctrine');

/**
 * BaseNoticia
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $titulo
 * @property string $descripcion
 * @property string $ubicacion
 * @property integer $status
 * @property timestamp $fecha_reg
 * @property timestamp $fecha_fin
 * @property string $img1
 * @property string $img2
 * @property string $img3
 * 
 * @method integer   getId()          Returns the current record's "id" value
 * @method string    getTitulo()      Returns the current record's "titulo" value
 * @method string    getDescripcion() Returns the current record's "descripcion" value
 * @method string    getUbicacion()   Returns the current record's "ubicacion" value
 * @method integer   getStatus()      Returns the current record's "status" value
 * @method timestamp getFechaReg()    Returns the current record's "fecha_reg" value
 * @method timestamp getFechaFin()    Returns the current record's "fecha_fin" value
 * @method string    getImg1()        Returns the current record's "img1" value
 * @method string    getImg2()        Returns the current record's "img2" value
 * @method string    getImg3()        Returns the current record's "img3" value
 * @method Noticia   setId()          Sets the current record's "id" value
 * @method Noticia   setTitulo()      Sets the current record's "titulo" value
 * @method Noticia   setDescripcion() Sets the current record's "descripcion" value
 * @method Noticia   setUbicacion()   Sets the current record's "ubicacion" value
 * @method Noticia   setStatus()      Sets the current record's "status" value
 * @method Noticia   setFechaReg()    Sets the current record's "fecha_reg" value
 * @method Noticia   setFechaFin()    Sets the current record's "fecha_fin" value
 * @method Noticia   setImg1()        Sets the current record's "img1" value
 * @method Noticia   setImg2()        Sets the current record's "img2" value
 * @method Noticia   setImg3()        Sets the current record's "img3" value
 * 
 * @package    galeno
 * @subpackage model
 * @author     Enimados
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseNoticia extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('noticia');
        $this->hasColumn('id', 'integer', 6, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 6,
             ));
        $this->hasColumn('titulo', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('descripcion', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('ubicacion', 'string', 120, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 120,
             ));
        $this->hasColumn('status', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fecha_reg', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('fecha_fin', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('img1', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('img2', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('img3', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}